In [ ]:
#Importation des bibliothèques
import numpy as np
import math
from tabulate import tabulate

**Q matrix**

In [ ]:
#Définition de la forme de l'environnement (ses positions)
environment_rows = 10
environment_columns = 10
#Création un tableau numpy 3D pour contenir la matrice Q actuelle pour chaque paire state/action : Q(s, a) 
#Le tableau contient 10 lignes et 10 colonnes (pour correspondre à l'environnement), ainsi qu'une troisième dimension "action".
#La valeur de chaque paire Q(état, action) est initialisée à 0.
q_values = np.zeros((environment_rows, environment_columns, 4))
print(q_values)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 

In [ ]:
#Code des actions: 0 = Haut, 1 = Droit, 2 = Bas, 3 = Gauche
actions = ['H', 'D', 'B', 'G']

**Reward matrix**

In [ ]:
# Créeation d'un tableau numpy 2D pour contenir les récompenses pour chaque state 
# Le tableau contient 10 lignes et 10 colonnes
rewards = np.full((environment_rows, environment_columns), 1.)

# La récompense du Goal est fixée à 10 pour encourager le robot à l'atteindre
rewards[9, 9] = 10.

# Calcul des récompenses pour tous les autres états en fonction de la distance au Goal.
for x in range(environment_rows):
    for y in range(environment_columns):
        # Sauter le state Goal (il a déjà été défini).
        if (x, y) == (9, 9):
            continue
        
        # Calcul de la distance entre l'état actuel et le goal.
        distance = math.sqrt((x - 9)**2 + (y - 9)**2)
        
        # On met la récompense pour l'état actuel à l'inverse de la distance.
        rewards[x, y] = 1.0 / distance

#Définir une récompense négative pour les obstacles à -10 pour punir le robot.
rewards[0,5] = -10
rewards[0,6] = -10
rewards[3,3] = -10
rewards[3,4] = -10
rewards[6,5] = -10
rewards[6,6] = -10
# Affichage de la matrice de récompenses
rounded_rewards = np.round(rewards, 3)
print(tabulate(rounded_rewards, tablefmt='grid'))

+-------+-------+-------+---------+---------+---------+---------+-------+-------+--------+
| 0.079 | 0.083 | 0.088 |   0.092 |   0.097 | -10     | -10     | 0.108 | 0.11  |  0.111 |
+-------+-------+-------+---------+---------+---------+---------+-------+-------+--------+
| 0.083 | 0.088 | 0.094 |   0.1   |   0.106 |   0.112 |   0.117 | 0.121 | 0.124 |  0.125 |
+-------+-------+-------+---------+---------+---------+---------+-------+-------+--------+
| 0.088 | 0.094 | 0.101 |   0.108 |   0.116 |   0.124 |   0.131 | 0.137 | 0.141 |  0.143 |
+-------+-------+-------+---------+---------+---------+---------+-------+-------+--------+
| 0.092 | 0.1   | 0.108 | -10     | -10     |   0.139 |   0.149 | 0.158 | 0.164 |  0.167 |
+-------+-------+-------+---------+---------+---------+---------+-------+-------+--------+
| 0.097 | 0.106 | 0.116 |   0.128 |   0.141 |   0.156 |   0.171 | 0.186 | 0.196 |  0.2   |
+-------+-------+-------+---------+---------+---------+---------+-------+-------+--------+

**Fonctions d'aide**

In [ ]:
# Fonction pour vérifier si l'état actuel est un état terminal aka (goal)
def is_terminal_state(actual_x, actual_y):
  # Si la récompense pour cet état est différente de 10, alors il ne s'agit pas d'un état terminal. 
  if rewards[actual_x, actual_y] != 10:
    return False
  else:
    return True
# Fonction pour choisir un état de départ aléatoire pour boucler dans l'environnement
def get_random_starting_location():
  actual_x = np.random.randint(environment_rows)
  actual_y = np.random.randint(environment_columns)
  # Continuer à choisir des index de lignes et de colonnes aléatoires même lorsque le goal est atteint
  while is_terminal_state(actual_x, actual_y):
    actual_x = np.random.randint(environment_rows)
    actual_y = np.random.randint(environment_columns)
  return actual_x, actual_y
  
#un algorithme avide d'epsilon qui choisira l'action suivante (c'est-à-dire l'endroit où se déplacer ensuite)
def choose_next_action(actual_x, actual_y, epsilon):
  # Si une valeur choisie au hasard entre 0 et 1 est inférieure à epsilon
  # on choisit alors la valeur la plus prometteuse de la matrice Q pour cet état.
  if np.random.random() < epsilon:
    return np.argmax(q_values[actual_x, actual_y])
  # Sinon on choisit une action aléatoire
  else: 
    return np.random.randint(4)

# Fonction qui obtiendra la prochaine position "état suivant" en fonction de l'action choisie.
def get_next_state(actual_x, actual_y, action_index):
  next_x = actual_x
  next_y = actual_y
  if actions[action_index] == 'H' and actual_x > 0:
    next_x -= 1
  elif actions[action_index] == 'D' and actual_y < environment_columns - 1:
    next_y += 1
  elif actions[action_index] == 'B' and actual_x < environment_rows - 1:
    next_x += 1
  elif actions[action_index] == 'G' and actual_y > 0:
    next_y -= 1
  return next_x, next_y

# Fonction qui trouvera le chemin optimale entre n'importe quel état initial et l'état finale
def shortest_path(start_x, start_y):
  # Retourner immédiatement si l'état initiale est l'état finale
  if is_terminal_state(start_x, start_y):
    return []
  else:
    actual_x, actual_y = start_x, start_y
    shortest_path = []
    shortest_path.append([actual_x, actual_y])
    # Se déplacer sans arrêt le long du chemin jusqu'à ce que nous atteignions le goal
    while not is_terminal_state(actual_x, actual_y):
      # On obtient l'action optimale à prendre
      action_index = choose_next_action(actual_x, actual_y,1)
      # Se déplacer vers l'état suivant suivant sur le chemin, et ajouter le nouvel état à la liste
      next_x, next_y = get_next_state(actual_x, actual_y, action_index)
      if (next_x,next_y != actual_x,actual_y):
        actual_x,actual_y = next_x,next_y
        shortest_path.append([actual_x, actual_y])
      else:
        continue
    return shortest_path

**Learning episodes**

In [ ]:
# Le pourcentage de temps où nous devrions prendre l'action optimale (au lieu d'une action aléatoire)
epsilon = 0.9 
# Paramètre d'apprentissage gamma
gamma = 0.7

# Exécuter 1000 épisodes d'entrainement
for episode in range(1000):
  # On choisit un état initiale aléatoire
  x, y = get_random_starting_location()
  # On explore notre environment jusqu'à ce qu'on arrive à l'état finale
  while not is_terminal_state(x, y):
    # On choisit une action pour se déplacer
    action_index = choose_next_action(x, y, epsilon)
    # On se déplace vers le prochain état à l'aide de l'action choisie
    past_x, past_y = x, y # on stocke l'ancien état
    x, y = get_next_state(x, y, action_index)
    # On reçoit la récompense du passage à l'état suivant
    # On calcule les nouvelles valeurs de la matrice Q pour l'ancien état
    reward = rewards[x, y]
    new_q_value = reward + (gamma * np.max(q_values[x, y]))
    # On met à jour la valeur Q pour l'ancien état et l'action performée
    q_values[past_x, past_y, action_index] = new_q_value

# Après l'exécution de 1000 épisodes, on affiche un message
print('Exploration terminée !')
# Affichage de la matrice Q
print(q_values)

Exploration terminée !
[[[  0.33291555   0.36335447   0.29721072   0.        ]
  [  0.32761027   0.39862343   0.40044142   0.30707465]
  [  0.30106303   0.44416805   0.30483558   0.28328873]
  [  0.20246557   0.           0.5024543    0.        ]
  [  0.32375945  -9.53923389   0.57246928   0.        ]
  [ -9.54332907  -9.74691448   0.66194075   0.        ]
  [-10.           0.65488979   0.          -9.66555356]
  [  0.65488979   0.78060651   0.57969067  -9.54157715]
  [  0.78060651   0.95739284   0.5298182    0.65488979]
  [  0.37035844   0.95739284   1.2089739    0.78060651]]

 [[  0.30595034   0.40044142   0.           0.3264389 ]
  [  0.32761027   0.4457901    0.           0.36335447]
  [  0.39862343   0.5024543    0.32702553   0.34937827]
  [  0.43965268   0.57246928   0.57493472   0.4457901 ]
  [  0.49785708   0.           0.66638499   0.        ]
  [ -9.71909882   0.52282461   0.7859105    0.36739584]
  [ -9.54157715   0.57969067   0.49728366   0.47778063]
  [  0.65488979   0.529

**Chemin optimale**

In [ ]:
# Afficher quelques chemins optimales
print(shortest_path(8, 9))
print(shortest_path(0, 0))

[[8, 9], [9, 9]]
[[0, 0], [0, 1], [1, 1], [1, 2], [1, 3], [2, 3], [2, 4], [2, 5], [3, 5], [4, 5], [5, 5], [5, 6], [5, 7], [6, 7], [7, 7], [7, 8], [8, 8], [8, 9], [9, 9]]
